spring:
    application:
      name: SMPP Pool Demo Application

smpp:
  client:
    host: 127.0.0.1
    port: 8056
    ssl: false
    systemid: systemid
    password: password
    system-type: cp
  server:
    port: 8056

logging:
  level:
    org.jsmpp: warn
    org.springframework: warn
    com.github.pmoerenhout: info
    com.github.pmoerenhout.jsmpp.pool: info
    com.github.pmoerenhout.jsmpp.pool.demo: info
    com.github.pmoerenhout.jsmpp.pool.server: info
